name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    # - name: Login Dockerhub
    #   env:
    #     DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    #     DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
    #   run: echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - name: Pull Server Image
      run: sudo docker pull mwajoe/me:extrasize_server
    - name: Pull Client Image
      run: sudo docker pull mwajoe/me:extrasize_client
    - name: Delete Old Server container
      run: sudo docker rm -f me:extrasize_server || true
    - name: Delete Old Client container
      run: sudo docker rm -f me:extrasize_client || true
    - name: Run new Server container
      run: sudo docker run -d -p 8000:8000 -- name extrasize_server mwajoe/me:extrasize_server
    - name: Run new Client container
      run: sudo docker run -d -p 8000:8000 -- name extrasize_client mwajoe/me:extrasize_client
