name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Server Image
        run: docker pull ianwu1992/cmpt_276_project_group_20-server:latest
      - name: Pull Client Image
        run: docker pull ianwu1992/cmpt_276_project_group_20-client:latest
      - name: Delete Old Server Container
        run: docker rm -f extrasize_server || true
      - name: Delete Old Client Container
        run: docker rm -f extrasize_client || true
      - name: Run New Server Container
        run: docker run -d -p 8000:8000 --name extrasize_server ianwu1992/cmpt_276_project_group_20-server:latest
      - name: Run New Client Container
        run: docker run -d -p 5173:80 --name extrasize_client ianwu1992/cmpt_276_project_group_20-client:latest
