name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Build the Client Docker image
        run: docker build . --file Client/Dockerfile --tag ianwu1992/cmpt_276_project_group_20-client:latest

      - name: Build the Server Docker image
        run: docker build . --file Server/Dockerfile --tag ianwu1992/cmpt_276_project_group_20-server:latest

      - name: Push Client to Dockerhub
        run: docker push ianwu1992/cmpt_276_project_group_20-client:latest

      - name: Push Server to Dockerhub
        run: docker push ianwu1992/cmpt_276_project_group_20-server:latest
